_wandb:
    value:
        cli_version: 0.19.0
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 9
                - 53
                - 55
                - 77
                - 103
            "2":
                - 1
                - 5
                - 9
                - 53
                - 55
                - 77
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.10.15
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
accelerator:
    value: gpu
activation:
    value: Tanh
add_variable_name_prefix_in_ckpt:
    value: false
add_variable_name_prefix_in_pyg:
    value: false
data_split:
    value:
        - 80
        - 10
        - 10
devices:
    value: 2
emb_dim:
    value: 12
emb_hidden:
    value: 1024
factor:
    value: 0.7
hard_cuts:
    value:
        pt:
            - 1000
            - .inf
input_dir:
    value: /mnt/data2/data/ATLAS-P2-RUN4-03-00-00_Rel.24_ttbar_uncorr_pu200_v9
knn:
    value: 50
knn_val:
    value: 1000
lr:
    value: 0.01
margin:
    value: 0.1
max_epochs:
    value: 10
metric_mode:
    value: max
metric_to_monitor:
    value: f1
model:
    value: MetricLearning
nb_layer:
    value: 4
node_features:
    value:
        - r
        - phi
        - z
node_scales:
    value:
        - 1000
        - 3.14
        - 1000
nodes:
    value: 1
patience:
    value: 10
points_per_batch:
    value: 50000
project:
    value: Giulia_testing
r_train:
    value: 0.1
randomisation:
    value: 1
stage:
    value: graph_construction
stage_dir:
    value: training_stage
train_undirected:
    value: true
undirected:
    value: true
variable_with_prefix:
    value: true
warmup:
    value: 5
weighting:
    value:
        - conditions:
            "y": false
          weight: 1
        - conditions:
            "y": true
          weight: 0
        - conditions:
            nhits:
                - 3
                - .inf
            pdgId:
                - not_in
                - - 11
                  - -11
            primary: true
            pt:
                - 1000
                - .inf
            "y": true
          weight: 3
