_wandb:
    value:
        cli_version: 0.19.0
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 9
                - 53
                - 55
                - 77
                - 103
            "2":
                - 1
                - 5
                - 9
                - 53
                - 55
                - 77
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.10.15
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
